packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild
  - leveldown
  - lmdb
  - msgpackr-extract
  - protobufjs

linkWorkspacePackages: true

onlyBuiltDependencies:
  - c-kzg

preferWorkspacePackages: true
